name: Release

on:
  push:
    branches:
      - release

permissions:
  contents: write # to be able to publish a GitHub release
  issues: write # to be able to comment on released issues
  pull-requests: write # to be able to comment on released pull requests
  id-token: write # to enable use of OIDC for trusted publishing and npm provenance
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      git_tag: ${{ steps.semantic-release.outputs.git_tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24.x"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm run build

      - name: Release
        id: semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npx semantic-release

          git_tag="$(git tag --points-at HEAD | tail -n 1)"

          if [ -n "$git_tag" ]; then
            echo "git_tag=$git_tag" >> "$GITHUB_OUTPUT"
          fi
